name = "sharex-r2"
compatibility_date = "2022-04-22"
main = "./dist/index.mjs"
account_id = "8be772befd147a8df540aae0fa15c047"
workers_dev = false
logpush = true
# minify = true
upload_source_maps = true
routes = [
	{pattern = "r2-sharex.cyberjake.xyz", custom_domain = true},
]

analytics_engine_datasets = [
    {binding = "AE", dataset = "r2-sharex"}
]

tail_consumers = [
  { service = "worker-ae-analytics", environment = "production" }
]

[[r2_buckets]]
bucket_name = "sharex-files"
preview_bucket_name = "sharex-files"
binding = "R2_BUCKET"

[build]
command = "npm run build"


