name = "sharex-r2"
account_id = "8be772befd147a8df540aae0fa15c047"
workers_dev = false
routes = [
	{pattern = "r2-sharex.cyberjake.xyz", custom_domain = true},
]

compatibility_date = "2022-04-22"
main = "./dist/index.mjs"

[build]
command = "npm run build"

[[r2_buckets]]
bucket_name = "sharex-files"
preview_bucket_name = "sharex-files"
binding = "R2_BUCKET"

analytics_engine_datasets = [
    {binding = "AE", dataset = "r2-sharex"}
]
tail_consumers = [
  { service = "worker-ae-analytics", environment = "production" }
]