name: Build
on:
  push:
  pull_request:
  repository_dispatch:

env:
  NODE_VERSION: 20.x
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    # always run in pull request, or repository_dispatch
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'repository_dispatch'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v3
        with:
          run_install: false

      - name: Get pnpm store directory
        run: |
            echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Restore NPM cache
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install 
      - run: pnpm run test

      - name: Publish
      # only publish if a direct `push`/`repository_dispatch`
        uses: cloudflare/wrangler-action@v3.13.1
        if: github.event_name == 'repository_dispatch' || github.event_name == 'push'
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish
          secrets: |
            AUTH_KEY
        env:
          NODE_ENV: production
          AUTH_KEY: ${{ secrets.AUTH_KEY }}