name: Build
on:
  push:
  pull_request:
  repository_dispatch:

env:
  NODE_VERSION: 24.x
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    # always run in pull request, or repository_dispatch
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'repository_dispatch'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        name: Install pnpm
        with:
          version: 11
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@65d868f8d4d85d7d4abb7de0875cde3fcc8798f5
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - run: pnpm run lint

      - name: Publish
      # only publish if a direct `push`/`repository_dispatch`
        uses: cloudflare/wrangler-action@v4
        if: github.event_name == 'repository_dispatch' || github.event_name == 'push'
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish
          secrets: |
            AUTH_KEY
        env:
          NODE_ENV: production
          AUTH_KEY: ${{ secrets.AUTH_KEY }}